package rocketniko:redis@0.0.1;

interface types {
    variant error {
        /// Operation against a key holding the wrong kind of value
        wrong-type,
        other(string),
    }

    type key-type = string;

    variant value-type {
        %bool(bool),
        int(s64),
        float(f64),
        %string(string),
        buffer(list<u8>),

        null,
        no-reply,
    }

}

/// identifiers that happen to be a WIT keyword need to be prefixed with %
interface %string {
    use types.{error, key-type, value-type};

    /// Returns the string value of a key
    get: func(key: key-type) -> result<string, error>;

    /// Sets the string value of a key, ignoring its type.
    set: func(key: key-type, value: value-type) -> result<_, error>;
}


world redis {
    export types;
    export %string;
}
