name: Taranaki

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        python -m pip install uv > /dev/null
        cargo --version
        cargo fmt --check
        uvx ruff check


  version:
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
    - id: set-version
      shell: bash
      run: |
        version="v0.0.0"
        if [[ "${{ github.event_name }}" == "release" ]]; then 
          version="${{ github.event.release.tag_name }}"
        fi
        echo "version=$version" >> $GITHUB_OUTPUT


  build-python:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v5

    - name: Build Wheel
      run: |
        python -m pip install uv > /dev/null
        uv version "$VERSION"
        uv build
        uv run taranaki version
      env:
        VERSION: ${{needs.version.outputs.version}}

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: python
        path: dist/
        retention-days: 1


  build:
    runs-on: ubuntu-latest
    needs: version
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            target: x86_64-unknown-linux-gnu
          - arch: arm64
            target: aarch64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v5

    - name: Install target
      shell: bash
      run: |
        rustup target add ${{ matrix.target }}
        if [[ ${{ matrix.arch }} == "arm64" ]]; then
          sudo apt install -y gcc-aarch64-linux-gnu
        fi

    #- name: Setup Cache
    #  uses: Swatinem/rust-cache@v2

    - name: Build
      shell: bash
      run: |
        python tools/update-version.py "$VERSION"
        if [[ ${{ matrix.target }} == "aarch64-unknown-linux-gnu" ]]; then
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
        fi
        cargo build --release --locked --target ${{ matrix.target }}
        file target/${{ matrix.target }}/release/*.so
        sha256sum target/${{ matrix.target }}/release/*.so
      env:
        VERSION: ${{needs.version.outputs.version}}

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: release-${{ matrix.arch }}
        path: target/${{ matrix.target }}/release/*.so
        retention-days: 1


  build-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Build Docker
      run: |
        exit 1
        cp target/release/libtaranaki_python.so docker/
        docker build --tag taranaki:latest docker/
        docker image save -o docker/taranaki.docker taranaki:latest

    - name: Test Docker
      run: |
        docker run --rm -d \
            --name taranaki \
            -p 127.0.0.1:6379:6379 \
            taranaki:latest

        uv run --with pytest pytest
        docker rm -f taranaki


  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/setup-uv@v8.1.0

    - name: Download artifacts
      uses: actions/download-artifact@v7
      with:
        name: release-${{ matrix.arch }}
        path: target/release/

    - name: Fix permissions
      run: |
        chmod 555 target/release/*.so
        ls -l target/release/

    - name: Test Redis
      run: |
        docker run --rm -d \
            --platform "linux/${{ matrix.arch }}" \
            --name redis \
            -p 127.0.0.1:6379:6379 \
            --volume $PWD:/app \
            redis:7.2.13 \
            redis-server \
            --loadmodule "/app/target/release/libtaranaki_python.so"
        uv run --with pytest pytest
        docker rm -f redis

    - name: Test Valkey
      run: |
        docker run --rm -d \
            --platform "linux/${{ matrix.arch }}" \
            --name valkey \
            -p 127.0.0.1:6379:6379 \
            --volume $PWD:/app \
            valkey/valkey:9.0.3 \
            valkey-server \
            --loadmodule "/app/target/release/libtaranaki_python.so"
        uv run --with pytest pytest
        docker rm -f valkey


  release-assets:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v7
      with:
        name: artifacts
        path: artifacts/

    - name: Upload release assets
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: |
          artifacts/VERSION
          artifacts/COMMIT-SHA
          artifacts/python/*.whl
          artifacts/lib/*.so


  release-pypi:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      # mandatory for trusted publishing
      id-token: write
      contents: read
    environment:
      name: pypi
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v7
      with:
        name: artifacts
        path: artifacts/

    #- name: Publish to PyPI
    #  uses: pypa/gh-action-pypi-publish@release/v1
    #  with:
    #    packages-dir: artifacts/python/
    #    print-hash: true


  release-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: read
    environment:
      name: docker
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v7
      with:
        name: artifacts
        path: artifacts/

    - name: Docker import
      run: |
        docker import artifacts/docker/taranaki.docker taranaki:latest
        docker image ls

    - name: Docker login
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker push
      run: |
        docker tag taranaki:latest xelato/taranaki:latest
        docker push xelato/taranaki:latest
