name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate
      run: |
        cargo --version
        cargo fmt --check

    - name: Build
      run: |
        cargo build --release
        ls -l target/release/*.so
        sha256sum target/release/*.so
        file target/release/*.so

    - name: Test Redis
      run: |
        docker run --rm -d \
            --name redis \
            -p 127.0.0.1:6379:6379 \
            --volume $PWD:/app \
            redis:7.2.13 \
            redis-server \
            --loadmodule "/app/target/release/libtaranaki_python.so" \
            --loadmodule "/app/target/release/libtaranaki_wasm.so"

        uv run --with pytest pytest
        docker rm -f redis

    - name: Test Valkey
      run: |
        docker run --rm -d \
            --name valkey \
            -p 127.0.0.1:6379:6379 \
            --volume $PWD:/app \
            redis:7.2.13 \
            redis-server \
            --loadmodule "/app/target/release/libtaranaki_python.so" \
            --loadmodule "/app/target/release/libtaranaki_wasm.so"

        uv run --with pytest pytest
        docker rm -f valkey
