name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: |
        python -m pip install uv > /dev/null

    - name: Validate
      run: |
        cargo --version
        cargo fmt --check

    - name: Version
      run: |
        python tools/update-version.py v99.99.99
        uv version `cat VERSION`

    - name: Build Wheel
      run: |
        uv build
        ls -l dist/
        uv run taranaki version

    - name: Build
      run: |
        cargo build --release
        ls -l target/release/*.so
        sha256sum target/release/*.so
        file target/release/*.so

    - name: Build Docker
      run: |
        cp target/release/libtaranaki_python.so docker/
        docker build --tag taranaki:latest docker/

    - name: Test Redis
      run: |
        docker run --rm -d \
            --name redis \
            -p 127.0.0.1:6379:6379 \
            --volume $PWD:/app \
            redis:7.2.13 \
            redis-server \
            --loadmodule "/app/target/release/libtaranaki_python.so"

        uv run --with pytest pytest
        docker rm -f redis

    - name: Test Valkey
      run: |
        docker run --rm -d \
            --name valkey \
            -p 127.0.0.1:6379:6379 \
            --volume $PWD:/app \
            valkey/valkey:9.0.3 \
            valkey-server \
            --loadmodule "/app/target/release/libtaranaki_python.so"

        uv run --with pytest pytest
        docker rm -f valkey

    - name: Test Docker
      run: |
        docker run --rm -d \
            --name taranaki \
            -p 127.0.0.1:6379:6379 \
            taranaki:latest

        uv run --with pytest pytest
        docker rm -f taranaki
