name: Wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull wit definition
      uses: xelato/wasm-action@main
      with:
        action: pull
        registry: wa.dev
        package: ao:kv@0.0.1
