name: Wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Provide cargo binstall
      uses: cargo-bins/cargo-binstall@main
    - name: Install dependencies
      run: |
        cargo binstall wasm-tools
        cargo binstall wkg
        cargo binstall warg-cli
        sudo apt install -y just
