name: Wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Provide cargo binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install dependencies
      run: |
        cargo binstall wkg
        sudo apt-get install -y just

    - name: Validate WIT
      run: |
        just wit-build
        ls -l *.wasm

    - name: Publish packages
      uses: xelato/wasm-publish-action
